---
name: Object-Simple-Mixin-AttrNames
version: 0.0203
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Mixin class to get attribute names for Object::Simple
license: perl
resources:
  license: ~
build_requires:
  Object::Simple: 2.0003
  Test::More: 0
provides:
  Object::Simple::Mixin::AttrNames:
    file: lib/Object/Simple/Mixin/AttrNames.pm
    version: 0.0203
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
